In [1]:
import pandas as pd
import numpy as np
from scipy.stats import norm

# Format replication modeling input

In [2]:
ox = pd.read_table("~/project-zarlab/CFW/MegaAnalysis_CFW_2019_Summary_Statistics/Flint_July14/OXPeaks160620.txt")
ox.head()

,phenotype,marker,chr,pos,ox.freq,ox.logp,ox.beta,ox.se,ox.sample,combined.freq,...,ox2.freq,ox2.logp,ox2.beta,ox2.se,ox2.sample,uc.freq,uc.logp,uc.beta,uc.se,uc.sample
0,EDL.assoc.90info.txt.gz,chr10_20880356,10,20880356,0.052,3.171812,0.249111,0.073137,NaN,0.050,...,0.059,0.241421,0.054470,0.096746,NaN,0.046,0.464656,-0.099522,0.104913,NaN
1,EDL.assoc.90info.txt.gz,chr11_32830102,11,32830102,0.199,3.226037,-0.140369,0.040802,NaN,0.776,...,0.793,0.004771,-0.000795,0.058055,NaN,0.732,0.322724,-0.028525,0.039974,NaN
2,EDL.assoc.90info.txt.gz,chr11_89084369,11,89084369,0.154,3.894995,-0.175912,0.045813,NaN,0.804,...,0.842,0.461254,0.059731,0.063316,NaN,0.729,0.395280,-0.029957,0.035766,NaN
3,EDL.assoc.90info.txt.gz,chr12_82747149,12,82747149,0.284,4.032674,0.139087,0.035504,NaN,0.296,...,0.293,0.520260,0.050914,0.049281,NaN,0.319,0.510405,0.045381,0.044562,NaN
4,EDL.assoc.90info.txt.gz,chr12_83885241,12,83885241,0.002,5.850875,25.557840,5.280891,NaN,0.002,...,0.002,1.331820,14.624920,7.338767,NaN,0.002,5.051284,36.453880,8.163695,NaN

In [3]:
sig = ox[ox["ox.logp"] > 5.675524]
sig.shape

(65, 29)

In [4]:
ox["phenotype"] = [p[:-20] for p in ox["phenotype"]]
ox.head()

,phenotype,marker,chr,pos,ox.freq,ox.logp,ox.beta,ox.se,ox.sample,combined.freq,...,ox2.freq,ox2.logp,ox2.beta,ox2.se,ox2.sample,uc.freq,uc.logp,uc.beta,uc.se,uc.sample
0,EDL,chr10_20880356,10,20880356,0.052,3.171812,0.249111,0.073137,NaN,0.050,...,0.059,0.241421,0.054470,0.096746,NaN,0.046,0.464656,-0.099522,0.104913,NaN
1,EDL,chr11_32830102,11,32830102,0.199,3.226037,-0.140369,0.040802,NaN,0.776,...,0.793,0.004771,-0.000795,0.058055,NaN,0.732,0.322724,-0.028525,0.039974,NaN
2,EDL,chr11_89084369,11,89084369,0.154,3.894995,-0.175912,0.045813,NaN,0.804,...,0.842,0.461254,0.059731,0.063316,NaN,0.729,0.395280,-0.029957,0.035766,NaN
3,EDL,chr12_82747149,12,82747149,0.284,4.032674,0.139087,0.035504,NaN,0.296,...,0.293,0.520260,0.050914,0.049281,NaN,0.319,0.510405,0.045381,0.044562,NaN
4,EDL,chr12_83885241,12,83885241,0.002,5.850875,25.557840,5.280891,NaN,0.002,...,0.002,1.331820,14.624920,7.338767,NaN,0.002,5.051284,36.453880,8.163695,NaN

In [5]:
ox_z = []
uc_z = []
for i in ox.index:
    p1 = 10** (- ox.loc[i, "ox.logp"])
    z1 = norm.ppf(p1)
    if ox.loc[i, "ox.beta"] > 0:
        z1 = -1 * z1
        
    p2 = 10** (- ox.loc[i, "uc.logp"])
    if np.isnan(p2):
        ox_z.append(np.nan)
        uc_z.append(np.nan)
        continue
    z2 = norm.ppf(p2)
    if ox.loc[i, "uc.beta"] > 0:
        z2 = -1 * z2
    
    ox_z.append(z1)
    uc_z.append(z2)

In [6]:
ox["z1"] = ox_z
ox["z2"] = uc_z
ox = ox.dropna(subset=["z1", "z2"])
ox.shape

(779, 31)

In [7]:
sig = ox[ox["ox.logp"] > 5.675524]
sig.shape

(65, 31)

In [8]:
sig.head()

,phenotype,marker,chr,pos,ox.freq,ox.logp,ox.beta,ox.se,ox.sample,combined.freq,...,ox2.beta,ox2.se,ox2.sample,uc.freq,uc.logp,uc.beta,uc.se,uc.sample,z1,z2
4,EDL,chr12_83885241,12,83885241,0.002,5.850875,25.557840,5.280891,NaN,0.002,...,14.624920,7.338767,NaN,0.002,5.051284,36.453880,8.163695,NaN,4.683557,4.291183
17,EDL,chr2_155814797,2,155814797,0.322,6.743446,0.180579,0.034471,NaN,0.669,...,0.092031,0.048837,NaN,0.653,4.671430,0.199711,0.046763,NaN,5.088417,4.092804
36,TA,chr11_88948500,11,88948500,0.178,6.809476,-0.219223,0.041622,NaN,0.820,...,0.031286,0.058153,NaN,0.817,0.875572,-0.078808,0.052438,NaN,-5.117180,-1.111500
42,TA,chr12_83514944,12,83514944,0.270,6.066448,-0.176681,0.035775,NaN,0.722,...,0.078202,0.050411,NaN,0.707,3.405282,-0.167612,0.047130,NaN,-4.784252,-3.357472
56,TA,chr2_155856984,2,155856984,0.323,8.165090,0.203094,0.034881,NaN,0.689,...,0.064061,0.050569,NaN,0.712,3.932701,0.175542,0.045385,NaN,5.677404,3.679685

In [9]:
keep_var = pd.read_table("/u/home/j/jzou1115/project-zarlab/CFW/confidence_interval_pipeline_out_pruned_ox_redo/qtls_independent.txt", header=None)[0]

In [10]:
sig["qtlid"] = [sig.loc[i, "phenotype"]+"_"+sig.loc[i, "marker"] for i in sig.index]
sig = sig[sig["qtlid"].isin(keep_var)]
sig.shape

/u/home/j/jzou1115/project-ernst/software/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

(32, 32)

In [11]:
datadir = "/u/home/j/jzou1115/project-zarlab/CFW/replication_pruned/input_phenotypes_pooled_2"
for p in set(sig["phenotype"]):
    print(p)
    sub = sig[sig["phenotype"]==p]
    if sub.shape[0] >= 2:
        outfile = datadir+"/"+p+"_ox_uc.txt"
        print(outfile)
        sub.to_csv(outfile, columns=["z1", "z2"], header=["s1", "s2"], sep="\t", index_label=False)

plantaris
TA
/u/home/j/jzou1115/project-zarlab/CFW/replication_pruned/input_phenotypes_pooled_2/TA_ox_uc.txt
gastroc
/u/home/j/jzou1115/project-zarlab/CFW/replication_pruned/input_phenotypes_pooled_2/gastroc_ox_uc.txt
EDL
/u/home/j/jzou1115/project-zarlab/CFW/replication_pruned/input_phenotypes_pooled_2/EDL_ox_uc.txt
activity.end
/u/home/j/jzou1115/project-zarlab/CFW/replication_pruned/input_phenotypes_pooled_2/activity.end_ox_uc.txt
tibia
/u/home/j/jzou1115/project-zarlab/CFW/replication_pruned/input_phenotypes_pooled_2/tibia_ox_uc.txt
activity.begin
/u/home/j/jzou1115/project-zarlab/CFW/replication_pruned/input_phenotypes_pooled_2/activity.begin_ox_uc.txt
activity.total
/u/home/j/jzou1115/project-zarlab/CFW/replication_pruned/input_phenotypes_pooled_2/activity.total_ox_uc.txt
soleus
/u/home/j/jzou1115/project-zarlab/CFW/replication_pruned/input_phenotypes_pooled_2/soleus_ox_uc.txt
bmd.a
weight
bmd
/u/home/j/jzou1115/project-zarlab/CFW/replication_pruned/input_phenotypes_pooled_2/bmd_ox_uc.txt
fc.context.corr

In [12]:
sig.head()

,phenotype,marker,chr,pos,ox.freq,ox.logp,ox.beta,ox.se,ox.sample,combined.freq,...,ox2.se,ox2.sample,uc.freq,uc.logp,uc.beta,uc.se,uc.sample,z1,z2,qtlid
4,EDL,chr12_83885241,12,83885241,0.002,5.850875,25.557840,5.280891,NaN,0.002,...,7.338767,NaN,0.002,5.051284,36.453880,8.163695,NaN,4.683557,4.291183,EDL_chr12_83885241
17,EDL,chr2_155814797,2,155814797,0.322,6.743446,0.180579,0.034471,NaN,0.669,...,0.048837,NaN,0.653,4.671430,0.199711,0.046763,NaN,5.088417,4.092804,EDL_chr2_155814797
36,TA,chr11_88948500,11,88948500,0.178,6.809476,-0.219223,0.041622,NaN,0.820,...,0.058153,NaN,0.817,0.875572,-0.078808,0.052438,NaN,-5.117180,-1.111500,TA_chr11_88948500
42,TA,chr12_83514944,12,83514944,0.270,6.066448,-0.176681,0.035775,NaN,0.722,...,0.050411,NaN,0.707,3.405282,-0.167612,0.047130,NaN,-4.784252,-3.357472,TA_chr12_83514944
56,TA,chr2_155856984,2,155856984,0.323,8.165090,0.203094,0.034881,NaN,0.689,...,0.050569,NaN,0.712,3.932701,0.175542,0.045385,NaN,5.677404,3.679685,TA_chr2_155856984